### ISSUE TITLE
Fails to build with flint2-2.8.0: error: static declaration of 'fmpz_kronecker' follows non-static declaration

### ISSUE THREAD

**Issue by yurivict** [fredrik-johansson/arb#373]
```
/wrkdirs/usr/ports/math/arb/work/arb-2.19.0/acb_modular/epsilon_arg.c:15:1: error: static declaration of 'fmpz_kronecker' follows non-static declaration
fmpz_kronecker(const fmpz_t a, const fmpz_t b)
^
/usr/local/include/flint/fmpz.h:648:15: note: previous declaration is here
FLINT_DLL int fmpz_kronecker(const fmpz_t a, const fmpz_t n);
              ^
1 error generated.
```

OS: FreeBSD 13
clang-11

**Comment by thofma** [comment]
Duplicate of #372

**Comment by fredrik-johansson** [comment]
Fixed in 2.20.
